### PR TITLE
Updated cookie policy to v3.6.3

### PR DESCRIPTION
**Pull request by samhotep**
## Done

- Updated the coookie policy to v3.6.3

## QA

- View the demo in an incognito web browser
- **Before** accepting cookies, 
  - Open developer tools and in the console type in `dataLayer`
  - There should be a `{"consent", "default"}` object in the dataLayer
- **After** accepting cookies, 
  - There should be a `{"consent", "update"}` object in the dataLayer

### CODE REVIEW

**Comment by laszlokajtar** [comment]
@samhotep the order of the scripts seems to be fine and they work as intended, however, the cookie policy popup appeared for me two times as if loaded twice

**Comment by samhotep** [comment]
> @samhotep the order of the scripts seems to be fine and they work as intended, however, the cookie policy popup appeared for me two times as if loaded twice

Please try again now

**Comment by laszlokajtar** [comment]
@samhotep now i don't see any Google consent on https://jp-ubuntu-com-474.demos.haus/

**Comment by samhotep** [comment]
> @samhotep now i don't see any Google consent on https://jp-ubuntu-com-474.demos.haus/

I just realised the Dockerfile was only building the js, not the cookie policy. It should be functional now

**Comment by laszlokajtar** [comment]
@samhotep lgtm!

**Pull request merged**
